# Generated by Django 5.2.12 on 2026-04-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_phone_number_userprofile_no_hp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('rfid_iron', models.CharField(blank=True, max_length=36, null=True)),
                ('rfid_qc', models.CharField(blank=True, max_length=36, null=True)),
                ('rfid_pqc', models.CharField(blank=True, max_length=36, null=True)),
                ('line', models.CharField(blank=True, max_length=30, null=True)),
                ('qc_good', models.PositiveSmallIntegerField(default=0)),
                ('qc_good_time', models.DateTimeField(blank=True, null=True)),
                ('qc_rework', models.PositiveSmallIntegerField(default=0)),
                ('qc_rework_time', models.DateTimeField(blank=True, null=True)),
                ('qc_reject', models.PositiveSmallIntegerField(default=0)),
                ('qc_reject_time', models.DateTimeField(blank=True, null=True)),
                ('pqc_good', models.PositiveSmallIntegerField(default=0)),
                ('pqc_good_time', models.DateTimeField(blank=True, null=True)),
                ('pqc_rework', models.PositiveSmallIntegerField(default=0)),
                ('pqc_rework_time', models.DateTimeField(blank=True, null=True)),
                ('pqc_reject', models.PositiveSmallIntegerField(default=0)),
                ('pqc_reject_time', models.DateTimeField(blank=True, null=True)),
                ('dryroom_ci', models.PositiveSmallIntegerField(default=0)),
                ('dryroom_ci_time', models.DateTimeField(blank=True, null=True)),
                ('dryroom_co', models.PositiveSmallIntegerField(default=0)),
                ('dryroom_co_time', models.DateTimeField(blank=True, null=True)),
                ('folding_ci', models.PositiveSmallIntegerField(default=0)),
                ('folding_ci_time', models.DateTimeField(blank=True, null=True)),
                ('folding_co', models.PositiveSmallIntegerField(default=0)),
                ('folding_co_time', models.DateTimeField(blank=True, null=True)),
                ('id_garment', models.AutoField(primary_key=True, serialize=False)),
                ('rfid_garment', models.CharField(max_length=36)),
                ('item', models.CharField(max_length=30)),
                ('buyer', models.CharField(max_length=30)),
                ('style', models.CharField(max_length=30)),
                ('wo', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('output', models.IntegerField(blank=True, null=True)),
                ('output_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'garment',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='line',
        ),
    ]
